import { Router } from 'express';
import healthRoutes          from './health.routes';
import authRoutes            from './auth.routes';
import leadRoutes            from './lead.routes';
import appointmentRoutes     from './appointment.routes';
import conversationRoutes    from './conversation.routes';
import businessRoutes        from './business.routes';
import notificationRoutes    from './notification.routes';
import organizationRoutes    from './organization.routes';
import invitationRoutes      from './invitation.routes';
import widgetRoutes          from './widget.routes';
import aiRoutes              from './ai.routes';
import crmRoutes             from './crm.routes';
import calendarRoutes        from './calendar.routes';
import automationRoutes      from './automation.routes';
import widgetPlatformRoutes  from './widget-platform.routes';
import dashboardRoutes       from './dashboard.routes';
import communicationsRoutes  from './communications.routes';
import agentsRoutes          from './agents.routes';
import platformRoutes        from './platform.routes';

const router = Router();

router.use('/health',          healthRoutes);
router.use('/auth',            authRoutes);
router.use('/organization',    organizationRoutes);
router.use('/invitations',     invitationRoutes);
router.use('/leads',           leadRoutes);
router.use('/appointments',    appointmentRoutes);
router.use('/conversations',   conversationRoutes);
router.use('/business',        businessRoutes);
router.use('/notifications',   notificationRoutes);
router.use('/widget',          widgetRoutes);
router.use('/ai',              aiRoutes);
router.use('/crm',             crmRoutes);
router.use('/calendar',        calendarRoutes);
router.use('/automation',      automationRoutes);
router.use('/widget-platform', widgetPlatformRoutes);
router.use('/dashboard',       dashboardRoutes);
router.use('/comms',           communicationsRoutes);
router.use('/agents',          agentsRoutes);
router.use('/platform',        platformRoutes);

export default router;
